name: ${APP_NAME}
options:
  bundleIdPrefix: ${BUNDLE_ID_PREFIX}
  deploymentTarget:
    iOS: "18.0"
    macOS: "15.0"
  createIntermediateGroups: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: "complete"
    DEVELOPMENT_TEAM: ""
    ENABLE_USER_SCRIPT_SANDBOXING: "NO"

packages:
  ${APP_NAME}Kit:
    path: Packages/${APP_NAME}Kit

targets:
  ${APP_NAME}:
    type: application
    platform: iOS
    sources:
      - path: ${APP_NAME}
    resources:
      - path: ${APP_NAME}/Assets.xcassets
      - path: ${APP_NAME}/Preview Content
    info:
      path: ${APP_NAME}/Info.plist
    entitlements:
      path: ${APP_NAME}/${APP_NAME}.entitlements
    preBuildScripts:
      - name: "SwiftLint"
        script: |
          if command -v swiftlint >/dev/null 2>&1; then
            swiftlint lint --fix
          fi
        runOnlyWhenInstalling: false
        basedOnDependencyAnalysis: false
      - name: "SwiftFormat"
        script: |
          if command -v swift-format >/dev/null 2>&1; then
            swift-format -i -r "${SRCROOT}/${APP_NAME}"
          fi
        runOnlyWhenInstalling: false
        basedOnDependencyAnalysis: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_ID_PREFIX}.${APP_NAME}
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: ${APP_NAME}/Info.plist
        CODE_SIGN_ENTITLEMENTS: ${APP_NAME}/${APP_NAME}.entitlements
    dependencies:
      - package: ${APP_NAME}Kit

  ${APP_NAME}Tests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests
    dependencies:
      - target: ${APP_NAME}
    settings:
      GENERATE_INFOPLIST_FILE: true

schemes:
  ${APP_NAME}:
    build:
      targets:
        ${APP_NAME}: all
        ${APP_NAME}Tests: [test]
    test:
      targets:
        - ${APP_NAME}Tests